<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.wocommunity</groupId>
		<artifactId>womodular</artifactId>
		<version>1.0.0</version>
	</parent>
	<artifactId>wonder-modular-dtwgeneration</artifactId>
	<dependencies>
		<dependency>
			<groupId>org.wocommunity</groupId>
			<artifactId>wonder-modular-foundation</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>org.wocommunity</groupId>
			<artifactId>wonder-modular-eocontrol</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>org.wocommunity</groupId>
			<artifactId>wonder-modular-webobjects</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.webobjects</groupId>
			<artifactId>JavaDTWGeneration</artifactId>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<artifactSet>
								<includes>
									<include>com.webobjects:JavaDTWGeneration</include>
								</includes>
							</artifactSet>
							<filters>
								<filter>
									<artifact>*:*</artifact>
									<excludes>
										<exclude>KeyValueCodingProtectedAccessor.class</exclude>
									</excludes>
								</filter>
							</filters>
							<useDependencyReducedPomInJar>true</useDependencyReducedPomInJar>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-antrun-plugin</artifactId>
				<executions>
					<execution>
						<phase>package</phase>
						<goals><goal>run</goal></goals>
						<configuration>
							<target>
								<!-- Extract the JAR -->
								<unjar 
									src="${project.build.directory}/${project.build.finalName}.jar"
									dest="${project.build.directory}/extracted"
									/>
								<!-- Move Resources inside the extracted content -->
								<move todir="${project.build.directory}/extracted/META-INF/webobjects/Resources">
									<fileset dir="${project.build.directory}/extracted/Resources" />
								</move>
								<!-- Delete the old directory -->
								<delete dir="${project.build.directory}/extracted/Resources" />
								<!-- Repackage the jar now -->
								<jar destfile="${project.build.directory}/${project.build.finalName}.jar"
									basedir="${project.build.directory}/extracted"
									/>
							</target>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.moditect</groupId>
				<artifactId>moditect-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>add-module-info</id>
						<phase>package</phase>
						<goals>
							<goal>add-module-info</goal>
						</goals>
						<configuration>
							<jdepsExtraArgs>
								<jdepsExtraArg>--multi-release=${womodules.jvm.version}</jdepsExtraArg>
							</jdepsExtraArgs>
							<jvmVersion>${womodules.jvm.version}</jvmVersion>
							<module>
								<moduleInfo>
									<name>org.wocommunity.webobjects.dtwgeneration</name>
									<open>true</open>
									<requires>
										org.wocommunity.webobjects.foundation;
										org.wocommunity.webobjects.eocontrol;
										org.wocommunity.webobjects.webobjects;
									</requires>
									<exports>
										com.webobjects.directtoweb.generation;
									</exports>
								</moduleInfo>
							</module>
							<exclusions>
								<exclusion>
									<groupId>com.webobjects</groupId>
									<artifactId>JavaFoundation</artifactId>
								</exclusion>
								<exclusion>
									<groupId>io.github.wocommunity</groupId>
									<artifactId>foundation-patches</artifactId>
								</exclusion>
								<exclusion>
									<groupId>io.github.wocommunity</groupId>
									<artifactId>eocontrol-patches</artifactId>
								</exclusion>
								<exclusion>
									<groupId>com.webobjects</groupId>
									<artifactId>JavaEOControl</artifactId>
								</exclusion>
								<exclusion>
									<groupId>com.webobjects</groupId>
									<artifactId>JavaWebObjects</artifactId>
								</exclusion>
								<exclusion>
									<groupId>io.github.wocommunity</groupId>
									<artifactId>webobjects-patches</artifactId>
								</exclusion>
								<exclusion>
									<groupId>com.webobjects</groupId>
									<artifactId>JavaDTWGeneration</artifactId>
								</exclusion>
							</exclusions>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>