<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.wocommunity</groupId>
	<artifactId>womodular</artifactId>
	<version>1.0.1</version>
	<packaging>pom</packaging>
	<properties>
		<maven.compiler.release>25</maven.compiler.release>
		<wopatches.version>0.2.0</wopatches.version>
		<womodules.jvm.version>25</womodules.jvm.version>
	</properties>
	<name>WOModular</name>
	<description>A project to modularize WebObjects</description>
	<modules>
		<module>wonder-modular-foundation</module>
		<module>wonder-modular-eocontrol</module>
		<module>wonder-modular-eoaccess</module>
		<module>wonder-modular-jdbcadaptor</module>
		<module>wonder-modular-webobjects</module>
		<module>wonder-modular-directtoweb</module>
		<module>wonder-modular-eoproject</module>
		<module>wonder-modular-dtwgeneration</module>
	</modules>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.webobjects</groupId>
				<artifactId>JavaFoundation</artifactId>
				<version>5.4.3</version>
			</dependency>
			<dependency>
				<groupId>com.webobjects</groupId>
				<artifactId>JavaEOAccess</artifactId>
				<version>5.4.3</version>
			</dependency>
			<dependency>
				<groupId>com.webobjects</groupId>
				<artifactId>JavaEOControl</artifactId>
				<version>5.4.3</version>
			</dependency>
			<dependency>
				<groupId>com.webobjects</groupId>
				<artifactId>JavaEOProject</artifactId>
				<version>5.4.3</version>
			</dependency>
			<dependency>
				<groupId>com.webobjects</groupId>
				<artifactId>JavaJDBCAdaptor</artifactId>
				<version>5.4.3</version>
			</dependency>
			<dependency>
				<groupId>com.webobjects</groupId>
				<artifactId>JavaXML</artifactId>
				<version>5.4.3</version>
			</dependency>
			<dependency>
				<groupId>com.webobjects</groupId>
				<artifactId>JavaWOJSPServlet</artifactId>
				<version>5.4.3</version>
			</dependency>
			<dependency>
				<groupId>com.webobjects</groupId>
				<artifactId>JavaWebObjects</artifactId>
				<version>5.4.3</version>
			</dependency>
			<dependency>
				<groupId>com.webobjects</groupId>
				<artifactId>JavaDTWGeneration</artifactId>
				<version>5.4.3</version>
			</dependency>
			<dependency>
				<groupId>com.webobjects</groupId>
				<artifactId>JavaDirectToWeb</artifactId>
				<version>5.4.3</version>
			</dependency>
			<dependency>
				<groupId>io.github.wocommunity</groupId>
				<artifactId>foundation-patches</artifactId>
				<version>${wopatches.version}</version>
			</dependency>
			<dependency>
				<groupId>io.github.wocommunity</groupId>
				<artifactId>eocontrol-patches</artifactId>
				<version>${wopatches.version}</version>
			</dependency>
			<dependency>
				<groupId>io.github.wocommunity</groupId>
				<artifactId>eoaccess-patches</artifactId>
				<version>${wopatches.version}</version>
			</dependency>
			<dependency>
				<groupId>io.github.wocommunity</groupId>
				<artifactId>jdbcadaptor-patches</artifactId>
				<version>${wopatches.version}</version>
			</dependency>
			<dependency>
				<groupId>io.github.wocommunity</groupId>
				<artifactId>webobjects-patches</artifactId>
				<version>${wopatches.version}</version>
			</dependency>
			<dependency>
				<groupId>io.github.wocommunity</groupId>
				<artifactId>directtoweb-patches</artifactId>
				<version>${wopatches.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-antrun-plugin</artifactId>
					<version>3.1.0</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-shade-plugin</artifactId>
					<version>3.6.1</version>
				</plugin>
				<plugin>
					<groupId>org.moditect</groupId>
					<artifactId>moditect-maven-plugin</artifactId>
					<version>1.3.0.Final</version>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>