<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.wocommunity</groupId>
		<artifactId>womodular</artifactId>
		<version>1.0.0-SNAPSHOT</version>
	</parent>
	<artifactId>wonder-modular-eoaccess</artifactId>
	<dependencies>
		<dependency>
			<groupId>org.wocommunity</groupId>
			<artifactId>wonder-modular-foundation</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>org.wocommunity</groupId>
			<artifactId>wonder-modular-eocontrol</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>com.webobjects</groupId>
			<artifactId>JavaEOAccess</artifactId>
		</dependency>
		<dependency>
			<groupId>io.github.wocommunity</groupId>
			<artifactId>eoaccess-patches</artifactId>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<artifactSet>
								<includes>
									<include>io.github.wocommunity:eoaccess-patches</include>
									<include>com.webobjects:JavaEOAccess</include>
								</includes>
							</artifactSet>
							<useDependencyReducedPomInJar>true</useDependencyReducedPomInJar>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.moditect</groupId>
				<artifactId>moditect-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>add-module-info</id>
						<phase>package</phase>
						<goals>
							<goal>add-module-info</goal>
						</goals>
						<configuration>
							<jvmVersion>${womodules.jvm.version}</jvmVersion>
							<module>
								<moduleInfo>
									<name>org.wocommunity.webobjects.eoaccess</name>
									<requires>
										org.wocommunity.webobjects.foundation;
										org.wocommunity.webobjects.eocontrol;
									</requires>
									<exports>
										com.webobjects.eoaccess;
										com.webobjects.eoaccess.synchronization;
									</exports>
								</moduleInfo>
							</module>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>