<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.wocommunity</groupId>
		<artifactId>womodular</artifactId>
		<version>1.0.0-SNAPSHOT</version>
	</parent>
	<artifactId>wonder-modular-foundation</artifactId>
	<dependencies>
		<dependency>
			<groupId>io.github.wocommunity</groupId>
			<artifactId>foundation-patches</artifactId>
		</dependency>
		<dependency>
			<groupId>com.webobjects</groupId>
			<artifactId>JavaFoundation</artifactId>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<artifactSet>
								<includes>
									<include>io.github.wocommunity:foundation-patches</include>
									<include>com.webobjects:JavaFoundation</include>
								</includes>
							</artifactSet>
							<useDependencyReducedPomInJar>true</useDependencyReducedPomInJar>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-antrun-plugin</artifactId>
				<executions>
					<execution>
						<phase>package</phase>
						<goals><goal>run</goal></goals>
						<configuration>
							<target>
								<!-- Extract the JAR -->
								<unjar 
									src="${project.build.directory}/${project.build.finalName}.jar"
									dest="${project.build.directory}/extracted"
									/>
								<!-- Move Resources inside the extracted content -->
								<move todir="${project.build.directory}/extracted/META-INF/webobjects/Resources">
									<fileset dir="${project.build.directory}/extracted/Resources" />
								</move>
								<!-- Delete the old directory -->
								<delete dir="${project.build.directory}/extracted/Resources" />
								<!-- Repackage the jar now -->
								<jar destfile="${project.build.directory}/${project.build.finalName}.jar"
									basedir="${project.build.directory}/extracted"
									/>
							</target>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.moditect</groupId>
				<artifactId>moditect-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>add-module-info</id>
						<phase>package</phase>
						<goals>
							<goal>add-module-info</goal>
						</goals>
						<configuration>
							<jvmVersion>${womodules.jvm.version}</jvmVersion>
							<exclusions>
								<exclusion>
									<groupId>com.webobjects</groupId>
									<artifactId>JavaFoundation</artifactId>
								</exclusion>
								<exclusion>
									<groupId>io.github.wocommunity</groupId>
									<artifactId>foundation-patches</artifactId>
								</exclusion>
							</exclusions>
							<module>
								<moduleInfo>
									<name>org.wocommunity.webobjects.foundation</name>
									<open>true</open>
									<requires>
										java.naming;
										java.sql;
										java.xml;
									</requires>
									<exports>
										com.webobjects.foundation;
										com.webobjects.foundation.development;
										com.webobjects.foundation.xml;
									</exports>
									<uses>
										com.webobjects.foundation.development.NSBundleAdaptorProvider;
									</uses>
									<provides>
										com.webobjects.foundation.development.NSBundleAdaptorProvider with com.webobjects.foundation.development.CFBundleAdaptor, com.webobjects.foundation.development.JarBundleAdaptor, com.webobjects.foundation.development.JigsawBundleAdaptor, com.webobjects.foundation.development.JigsawJarBundleAdaptor, com.webobjects.foundation.development.MavenFluffyBunnyProjectAdaptor;
									</provides>
								</moduleInfo>
							</module>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>